// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN68JXTxNoh1SQYE2L6zi5VyJgwP5c8mc',
    appId: '1:433422940530:web:c51c65b2a69f5771a1c5eb',
    messagingSenderId: '433422940530',
    projectId: 'social-media-46a95',
    authDomain: 'social-media-46a95.firebaseapp.com',
    storageBucket: 'social-media-46a95.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtYsDHQhXkAMbgy9fOiBz9jmCxBVyv7Ow',
    appId: '1:433422940530:android:0ee8fb67802dec0ea1c5eb',
    messagingSenderId: '433422940530',
    projectId: 'social-media-46a95',
    storageBucket: 'social-media-46a95.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXpUWmiFZAZQDbSTJxYK52rTEQlJ_rinc',
    appId: '1:433422940530:ios:b00d4d441ce8f9a2a1c5eb',
    messagingSenderId: '433422940530',
    projectId: 'social-media-46a95',
    storageBucket: 'social-media-46a95.appspot.com',
    iosClientId: '433422940530-hanevohl3hsbmskei2p0bfgv46t3afat.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialMedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXpUWmiFZAZQDbSTJxYK52rTEQlJ_rinc',
    appId: '1:433422940530:ios:b00d4d441ce8f9a2a1c5eb',
    messagingSenderId: '433422940530',
    projectId: 'social-media-46a95',
    storageBucket: 'social-media-46a95.appspot.com',
    iosClientId: '433422940530-hanevohl3hsbmskei2p0bfgv46t3afat.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialMedia',
  );
}
